/** ISO 4217 currencies that have a minor unit. A code with no minor unit cannot store an exact amount, so it is not accepted. Naira is the home currency. */
export const HOME_CURRENCY = "NGN";

export interface CurrencyInfo {
  exponent: number;
  name: string;
}

export const CURRENCIES: Record<string, CurrencyInfo> = {
  AED: { exponent: 2, name: "UAE Dirham" },
  AFN: { exponent: 2, name: "Afghani" },
  ALL: { exponent: 2, name: "Lek" },
  AMD: { exponent: 2, name: "Armenian Dram" },
  AOA: { exponent: 2, name: "Kwanza" },
  ARS: { exponent: 2, name: "Argentine Peso" },
  AUD: { exponent: 2, name: "Australian Dollar" },
  AWG: { exponent: 2, name: "Aruban Florin" },
  AZN: { exponent: 2, name: "Azerbaijan Manat" },
  BAM: { exponent: 2, name: "Convertible Mark" },
  BBD: { exponent: 2, name: "Barbados Dollar" },
  BDT: { exponent: 2, name: "Taka" },
  BHD: { exponent: 3, name: "Bahraini Dinar" },
  BIF: { exponent: 0, name: "Burundi Franc" },
  BMD: { exponent: 2, name: "Bermudian Dollar" },
  BND: { exponent: 2, name: "Brunei Dollar" },
  BOB: { exponent: 2, name: "Boliviano" },
  BOV: { exponent: 2, name: "Mvdol" },
  BRL: { exponent: 2, name: "Brazilian Real" },
  BSD: { exponent: 2, name: "Bahamian Dollar" },
  BTN: { exponent: 2, name: "Ngultrum" },
  BWP: { exponent: 2, name: "Pula" },
  BYN: { exponent: 2, name: "Belarusian Ruble" },
  BZD: { exponent: 2, name: "Belize Dollar" },
  CAD: { exponent: 2, name: "Canadian Dollar" },
  CDF: { exponent: 2, name: "Congolese Franc" },
  CHE: { exponent: 2, name: "WIR Euro" },
  CHF: { exponent: 2, name: "Swiss Franc" },
  CHW: { exponent: 2, name: "WIR Franc" },
  CLF: { exponent: 4, name: "Unidad de Fomento" },
  CLP: { exponent: 0, name: "Chilean Peso" },
  CNY: { exponent: 2, name: "Yuan Renminbi" },
  COP: { exponent: 2, name: "Colombian Peso" },
  COU: { exponent: 2, name: "Unidad de Valor Real" },
  CRC: { exponent: 2, name: "Costa Rican Colon" },
  CUP: { exponent: 2, name: "Cuban Peso" },
  CVE: { exponent: 2, name: "Cabo Verde Escudo" },
  CZK: { exponent: 2, name: "Czech Koruna" },
  DJF: { exponent: 0, name: "Djibouti Franc" },
  DKK: { exponent: 2, name: "Danish Krone" },
  DOP: { exponent: 2, name: "Dominican Peso" },
  DZD: { exponent: 2, name: "Algerian Dinar" },
  EGP: { exponent: 2, name: "Egyptian Pound" },
  ERN: { exponent: 2, name: "Nakfa" },
  ETB: { exponent: 2, name: "Ethiopian Birr" },
  EUR: { exponent: 2, name: "Euro" },
  FJD: { exponent: 2, name: "Fiji Dollar" },
  FKP: { exponent: 2, name: "Falkland Islands Pound" },
  GBP: { exponent: 2, name: "Pound Sterling" },
  GEL: { exponent: 2, name: "Lari" },
  GHS: { exponent: 2, name: "Ghana Cedi" },
  GIP: { exponent: 2, name: "Gibraltar Pound" },
  GMD: { exponent: 2, name: "Dalasi" },
  GNF: { exponent: 0, name: "Guinean Franc" },
  GTQ: { exponent: 2, name: "Quetzal" },
  GYD: { exponent: 2, name: "Guyana Dollar" },
  HKD: { exponent: 2, name: "Hong Kong Dollar" },
  HNL: { exponent: 2, name: "Lempira" },
  HTG: { exponent: 2, name: "Gourde" },
  HUF: { exponent: 2, name: "Forint" },
  IDR: { exponent: 2, name: "Rupiah" },
  ILS: { exponent: 2, name: "New Israeli Sheqel" },
  INR: { exponent: 2, name: "Indian Rupee" },
  IQD: { exponent: 3, name: "Iraqi Dinar" },
  IRR: { exponent: 2, name: "Iranian Rial" },
  ISK: { exponent: 0, name: "Iceland Krona" },
  JMD: { exponent: 2, name: "Jamaican Dollar" },
  JOD: { exponent: 3, name: "Jordanian Dinar" },
  JPY: { exponent: 0, name: "Yen" },
  KES: { exponent: 2, name: "Kenyan Shilling" },
  KGS: { exponent: 2, name: "Som" },
  KHR: { exponent: 2, name: "Riel" },
  KMF: { exponent: 0, name: "Comorian Franc" },
  KPW: { exponent: 2, name: "North Korean Won" },
  KRW: { exponent: 0, name: "Won" },
  KWD: { exponent: 3, name: "Kuwaiti Dinar" },
  KYD: { exponent: 2, name: "Cayman Islands Dollar" },
  KZT: { exponent: 2, name: "Tenge" },
  LAK: { exponent: 2, name: "Lao Kip" },
  LBP: { exponent: 2, name: "Lebanese Pound" },
  LKR: { exponent: 2, name: "Sri Lanka Rupee" },
  LRD: { exponent: 2, name: "Liberian Dollar" },
  LSL: { exponent: 2, name: "Loti" },
  LYD: { exponent: 3, name: "Libyan Dinar" },
  MAD: { exponent: 2, name: "Moroccan Dirham" },
  MDL: { exponent: 2, name: "Moldovan Leu" },
  MGA: { exponent: 2, name: "Malagasy Ariary" },
  MKD: { exponent: 2, name: "Denar" },
  MMK: { exponent: 2, name: "Kyat" },
  MNT: { exponent: 2, name: "Tugrik" },
  MOP: { exponent: 2, name: "Pataca" },
  MRU: { exponent: 2, name: "Ouguiya" },
  MUR: { exponent: 2, name: "Mauritius Rupee" },
  MVR: { exponent: 2, name: "Rufiyaa" },
  MWK: { exponent: 2, name: "Malawi Kwacha" },
  MXN: { exponent: 2, name: "Mexican Peso" },
  MXV: { exponent: 2, name: "Mexican Unidad de Inversion (UDI)" },
  MYR: { exponent: 2, name: "Malaysian Ringgit" },
  MZN: { exponent: 2, name: "Mozambique Metical" },
  NAD: { exponent: 2, name: "Namibia Dollar" },
  NGN: { exponent: 2, name: "Naira" },
  NIO: { exponent: 2, name: "Cordoba Oro" },
  NOK: { exponent: 2, name: "Norwegian Krone" },
  NPR: { exponent: 2, name: "Nepalese Rupee" },
  NZD: { exponent: 2, name: "New Zealand Dollar" },
  OMR: { exponent: 3, name: "Rial Omani" },
  PAB: { exponent: 2, name: "Balboa" },
  PEN: { exponent: 2, name: "Sol" },
  PGK: { exponent: 2, name: "Kina" },
  PHP: { exponent: 2, name: "Philippine Peso" },
  PKR: { exponent: 2, name: "Pakistan Rupee" },
  PLN: { exponent: 2, name: "Zloty" },
  PYG: { exponent: 0, name: "Guarani" },
  QAR: { exponent: 2, name: "Qatari Rial" },
  RON: { exponent: 2, name: "Romanian Leu" },
  RSD: { exponent: 2, name: "Serbian Dinar" },
  RUB: { exponent: 2, name: "Russian Ruble" },
  RWF: { exponent: 0, name: "Rwanda Franc" },
  SAR: { exponent: 2, name: "Saudi Riyal" },
  SBD: { exponent: 2, name: "Solomon Islands Dollar" },
  SCR: { exponent: 2, name: "Seychelles Rupee" },
  SDG: { exponent: 2, name: "Sudanese Pound" },
  SEK: { exponent: 2, name: "Swedish Krona" },
  SGD: { exponent: 2, name: "Singapore Dollar" },
  SHP: { exponent: 2, name: "Saint Helena Pound" },
  SLE: { exponent: 2, name: "Leone" },
  SOS: { exponent: 2, name: "Somali Shilling" },
  SRD: { exponent: 2, name: "Surinam Dollar" },
  SSP: { exponent: 2, name: "South Sudanese Pound" },
  STN: { exponent: 2, name: "Dobra" },
  SVC: { exponent: 2, name: "El Salvador Colon" },
  SYP: { exponent: 2, name: "Syrian Pound" },
  SZL: { exponent: 2, name: "Lilangeni" },
  THB: { exponent: 2, name: "Baht" },
  TJS: { exponent: 2, name: "Somoni" },
  TMT: { exponent: 2, name: "Turkmenistan New Manat" },
  TND: { exponent: 3, name: "Tunisian Dinar" },
  TOP: { exponent: 2, name: "Pa’anga" },
  TRY: { exponent: 2, name: "Turkish Lira" },
  TTD: { exponent: 2, name: "Trinidad and Tobago Dollar" },
  TWD: { exponent: 2, name: "New Taiwan Dollar" },
  TZS: { exponent: 2, name: "Tanzanian Shilling" },
  UAH: { exponent: 2, name: "Hryvnia" },
  UGX: { exponent: 0, name: "Uganda Shilling" },
  USD: { exponent: 2, name: "US Dollar" },
  USN: { exponent: 2, name: "US Dollar (Next day)" },
  UYI: { exponent: 0, name: "Uruguay Peso en Unidades Indexadas (UI)" },
  UYU: { exponent: 2, name: "Peso Uruguayo" },
  UYW: { exponent: 4, name: "Unidad Previsional" },
  UZS: { exponent: 2, name: "Uzbekistan Sum" },
  VED: { exponent: 2, name: "Bolívar Soberano" },
  VES: { exponent: 2, name: "Bolívar Soberano" },
  VND: { exponent: 0, name: "Dong" },
  VUV: { exponent: 0, name: "Vatu" },
  WST: { exponent: 2, name: "Tala" },
  XAD: { exponent: 2, name: "Arab Accounting Dinar" },
  XAF: { exponent: 0, name: "CFA Franc BEAC" },
  XCD: { exponent: 2, name: "East Caribbean Dollar" },
  XCG: { exponent: 2, name: "Caribbean Guilder" },
  XOF: { exponent: 0, name: "CFA Franc BCEAO" },
  XPF: { exponent: 0, name: "CFP Franc" },
  YER: { exponent: 2, name: "Yemeni Rial" },
  ZAR: { exponent: 2, name: "Rand" },
  ZMW: { exponent: 2, name: "Zambian Kwacha" },
  ZWG: { exponent: 2, name: "Zimbabwe Gold" },
};

export function currencyInfo(code: string): CurrencyInfo | null {
  return CURRENCIES[code] ?? null;
}

export function listCurrencies(): { code: string; exponent: number; name: string }[] {
  return Object.entries(CURRENCIES)
    .map(([code, info]) => ({ code, exponent: info.exponent, name: info.name }))
    .sort((left, right) => {
      if (left.code === HOME_CURRENCY) return -1;
      if (right.code === HOME_CURRENCY) return 1;
      return left.code.localeCompare(right.code);
    });
}